apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      command:
        - dockerd
      tty: true
